// This file is not generated, but this comment is necessary to exclude it from StyleCop analysis 
// <auto-generated/> 
using MyProject.Global.Dtos;
using System.Collections.Generic;

namespace MyProject.Roles.Dto
{
    public class GetRoleForEditOutput
    {
        public RoleEditDto Role { get; set; }

        public List<FlatTreeSelectDto<string>> Permissions { get; set; }

        public List<string> GrantedPermissionNames { get; set; }
    }
}