// This file is not generated, but this comment is necessary to exclude it from StyleCop analysis 
// <auto-generated/> 

namespace MyProject.Global
{
    public class GlobalConst
    {
        public enum TrangThaiThucThiQueryConst
        {
            ThanhCong = 1,
            ThatBai,
        }

        public enum TrangThaiHieuLucConst
        {
            KhoiTao,
            HieuLuc,
            HetHieuLuc,
        }

        public enum TrangThaiDuyetConst
        {
            KhoiTao,
            ChoDuyet,
            DaDuyet,
            KhongDuyet,
        }

        public enum ReadExcelResultCodeConst
        {
            FileNotFound = 404,
            CantReadData = 500,
            OK = 200,
        }
    }
}
