// This file is not generated, but this comment is necessary to exclude it from StyleCop analysis 
// <auto-generated/> 
namespace MyProject.Authorization
{
    public static class PermissionNames
    {
        public const string Pages = "Pages";
        public const string Pages_Tenants = "Pages.Tenants";
        public const string Pages_Users = "Pages.Users";
        public const string Pages_QuanLyLichSuNguoiDung = "Pages.QuanLyLichSuNguoiDung";
        public const string Pages_Roles = "Pages.Roles";
    }
}
